name: CI
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"

  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cflags:
            - -fsanitize=address
            - -fsanitize=memory
            - -fsanitize=undefined
            - -fsanitize=dataflow
            - -fsanitize=safe-stack
          dependencies:
            - iwyu
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/ghaction-conan-cmake:latest
        with:
          cc: clang
          cflags: ${{ matrix.cflags }}
          dependencies: ${{ matrix.dependencies }}
